//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvotoApi.Connections {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistrarUris {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrarUris() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvotoApi.Connections.RegistrarUris", typeof(RegistrarUris).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users/changePassword.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to management/createblockchain.
        /// </summary>
        internal static string createBlockchain {
            get {
                return ResourceManager.GetString("createBlockchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string createUser {
            get {
                return ResourceManager.GetString("createUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users/{0}.
        /// </summary>
        internal static string deleteUser {
            get {
                return ResourceManager.GetString("deleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/customFields.
        /// </summary>
        internal static string getCustomFields {
            get {
                return ResourceManager.GetString("getCustomFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to management/results.
        /// </summary>
        internal static string getResults {
            get {
                return ResourceManager.GetString("getResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users/{0}.
        /// </summary>
        internal static string getUserById {
            get {
                return ResourceManager.GetString("getUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string getUsers {
            get {
                return ResourceManager.GetString("getUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings/list.
        /// </summary>
        internal static string listSettings {
            get {
                return ResourceManager.GetString("listSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users/{0}/confirmEmail.
        /// </summary>
        internal static string setEmailConfirmed {
            get {
                return ResourceManager.GetString("setEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users/customFields/update.
        /// </summary>
        internal static string updateCustomFields {
            get {
                return ResourceManager.GetString("updateCustomFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string updateSetting {
            get {
                return ResourceManager.GetString("updateSetting", resourceCulture);
            }
        }
    }
}
